{
 "title": "Responsive Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "tenant", "query": { "query": "label_values(tenant_id)" } },
   {
    "name": "application_id",
    "query": {
     "query": "label_values(responsive_application_id)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Num Running Containers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by(host_name) (kafka_streams_thread_process_rate{tenant_id=\"$tenant\", responsive_application_id=\"$application_id\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Process Rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (responsive_application_id) (kafka_streams_thread_process_rate{tenant_id='${tenant}', responsive_application_id='${application_id}'})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Append Rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (responsive_application_id) (diagnoser_latency_expected_partition_append_rate{tenant_id='${tenant}', responsive_application_id='${application_id}'})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Processing Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Current Process Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 14, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (responsive_application_id) (kafka_streams_thread_process_rate{tenant_id='${tenant}', responsive_application_id='${application_id}'})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Lag",
   "type": "table",
   "gridPos": { "h": 14, "w": 10, "x": 14, "y": 6 },
   "targets": [
    {
     "expr": "avg by (topic, partition, host_name, clientId) (kafka_streams_records_lag{tenant_id='${tenant}', responsive_application_id='${application_id}'})",
     "legendFormat": "{{topic}} [{{partition}}]"
    }
   ]
  },
  {
   "title": "Current Append Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 14, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (responsive_application_id) (diagnoser_latency_expected_partition_append_rate{tenant_id='${tenant}', responsive_application_id='${application_id}'})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Events Processed (Daily)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (topic) ((max by (topic, partition) (responsive_kafka_streams_source_offset_end{tenant_id='${tenant}', responsive_application_id='${application_id}'})) - (max by (topic, partition) (responsive_kafka_streams_source_offset_end{tenant_id='${tenant}', responsive_application_id='${application_id}'} offset 1d)))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Expected Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 20 },
   "targets": [
    {
     "expr": "max by (applicationId)(diagnoser_latency_expected_node_seconds{tenant_id='${tenant}', responsive_application_id='${application_id}'})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Lag (Graph)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 20 },
   "targets": [
    {
     "expr": "min by (topic, partition) (clamp_min(kafka_streams_records_lag{tenant_id='${tenant}', responsive_application_id='${application_id}'},0))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Processing Ratio",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "avg (kafka_streams_thread_commit_ratio{tenant_id='${tenant}', responsive_application_id='${application_id}'})",
     "legendFormat": "commit"
    },
    {
     "expr": "avg (kafka_streams_thread_poll_ratio{tenant_id='${tenant}', responsive_application_id='${application_id}'})",
     "legendFormat": "poll"
    },
    {
     "expr": "avg (kafka_streams_thread_process_ratio{tenant_id='${tenant}', responsive_application_id='${application_id}'})",
     "legendFormat": "process"
    },
    {
     "expr": "avg (kafka_streams_thread_punctuate_ratio{tenant_id='${tenant}', responsive_application_id='${application_id}'})",
     "legendFormat": "punctuate"
    }
   ]
  },
  {
   "title": "Rebalancing",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (responsive_application_id) (clamp_max(changes(kafka_streams_rebalance_rate{tenant_id='${tenant}',responsive_application_id='${application_id}'}[3m]), 1))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Partition Assignment",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "Partitions" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (host_name) (kafka_streams_assigned_partitions{tenant_id='${tenant}', responsive_application_id='${application_id}'})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}